###

POST https://yayawallet.com/api/en/transaction/search
YAYA-API-KEY: API_KEY
YAYA-API-TIMESTAMP: timestamp
YAYA-API-SIGN: signature
Content-Type: application/json

{
  "transaction_id": "cc504c23-0275-4adf-9e5d-f8535dbb1436"
}

###